name = "oisdrive-website"
compatibility_date = "2025-09-09"

# Cloudflare Pages configuration
[assets]
directory = ".next"


# This is for Cloudflare Pages deployment
# The actual deployment should be done through Cloudflare Pages dashboard
# or using: npx wrangler pages deploy .next --project-name=oisdrive-website

# Environment variables should be set in Cloudflare Pages dashboard
# MAILGUN_API_KEY - Set in Cloudflare Pages environment variables
# MAILGUN_DOMAIN - Set in Cloudflare Pages environment variables  
# MAILGUN_FROM_EMAIL - Set in Cloudflare Pages environment variables
# MAILGUN_URL - Set in Cloudflare Pages environment variables
