name = 'datarecoverysebsite'
compatibility_date = "2025-01-09"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration for Next.js runtime
# This configuration is for Cloudflare Pages with Next.js support

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Pages configuration
[pages]
# The build output directory for Next.js on Cloudflare Pages
pages_build_output_dir = ".next"

# Environment variables should be set in Cloudflare Pages dashboard
# MAILGUN_API_KEY - Set in Cloudflare Pages environment variables
# MAILGUN_DOMAIN - Set in Cloudflare Pages environment variables  
# MAILGUN_FROM_EMAIL - Set in Cloudflare Pages environment variables
# MAILGUN_URL - Set in Cloudflare Pages environment variables
